project/calculadora/urls.py
from django.urls import path
from . import views

app_name="calculadora"

urlpatterns = [
    path("", views.home, name="home"),

]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('productos/', include("productos.urls")),
    path('pruebas/', include("pruebas.urls")),
    path('calculadora/', include("calculadora.urls")),
]

project/core/urls.py
from django.urls import path
from . import views

app_name="core"

urlpatterns = [
    path('', views.home, name="home"),
]

project/productos/urls.py
from django.urls import path
from . import views

app_name="productos"

urlpatterns = [
    path('', views.home, name="home"),
]

project/pruebas/urls.py
from django.urls import path
from . import views

app_name="pruebas"

urlpatterns = [
    path('', views.home, name="home"),
    path('enviar_lista/', views.enviar_lista, name="enviar_lista"),
    path('select_productos/', views.select_productos, name="select_productos"),
]

project/calculadora/models.py
from django.db import models

# Create your models here.

project/productos/models.py
from django.db import models

# Create your models here.

class CategoriaProducto(models.Model):
    nombre=models.CharField(max_length=50)
    
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    categoria=models.ForeignKey(CategoriaProducto, on_delete=models.CASCADE)
    nombre=models.CharField(max_length=50, verbose_name="Producto")
    precio=models.IntegerField(blank=True, null=True, verbose_name="Precio Unitario")
    precio_doc=models.IntegerField(blank=True, null=True, verbose_name="Precio por docena")
    precio_media=models.IntegerField(blank=True, null=True, verbose_name="Precio por mitad")
    
    def __str__(self):
        return self.nombre

class Cliente(models.Model):
    nombre=models.CharField(max_length=50)
    email=models.EmailField()
    
    def __str__(self):
        return self.nombre
    
class Pedido(models.Model):
    numero=models.IntegerField(verbose_name="Número de Pedido") 
    fecha=models.DateField(verbose_name="Fecha")
    
    def __str__(self):
        return f"{self.numero}"

project/calculadora/views.py
from django.shortcuts import render
from . import funciones

def home(request):
    resultado = None  
    if request.method == 'POST':
        a = int(request.POST.get('a', 0))  
        b = int(request.POST.get('b', 0))  
        if 'sumar' in request.POST:
            resultado = funciones.sumar(a, b)
            return render(request, "calculadora/index.html", {'resultado': resultado})
        if 'restar' in request.POST:
            resultado = funciones.restar(a, b)
            return render(request, "calculadora/index.html", {'resultado': resultado})
        if 'multiplicar' in request.POST:
            resultado = funciones.multiplicar(a, b)
            return render(request, "calculadora/index.html", {'resultado': resultado})
        if 'dividir' in request.POST:
            resultado = funciones.dividir(a, b)
            return render(request, "calculadora/index.html", {'resultado': resultado})
        
    return render(request, "calculadora/index.html", {'resultado': resultado})

project/core/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,"core/index.html")

project/productos/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, "productos/index.html")

project/pruebas/views.py
from collections import defaultdict
from django.shortcuts import render
from productos.models import Producto
from . import funciones

def home(request):
    return render(request, "pruebas/index.html")

def enviar_lista(request):
    lista=[0,1,2,3,4,5]
    return render(request, "pruebas/components/lista.html", {'lista':lista})

def select_productos(request):
    categorias=funciones.select_productos()
    producto=None
    cantidad=0
    mensaje=None

    if request.method == 'POST':
        producto_id = request.POST.get('producto')
        cantidad = int(request.POST.get('cantidad'))
        if not producto_id:
            mensaje="Debe seleccionar un producto..."
        else:
            producto = Producto.objects.get(pk=producto_id)
            mensaje=None
 
 
    context = {
        'categorias': categorias,
        'producto':producto,
        'cantidad':cantidad,
        'mensaje':mensaje
    }
    
    return render(request, 'pruebas/components/select_productos/select_productos.html', context)

project/calculadora/templates/calculadora/components/resultado.html
{% if resultado != None %}
    <h2>Resultado: {{resultado}}</h2>   
{% endif %}


 

project/calculadora/templates/calculadora/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}
    <h1>Calculadora</h1>
    
    <form method="POST" action="{% url 'calculadora:home' %}">
        {% csrf_token %}
        <input type="number" name="a" id="a" placeholder="Ingrese un número" required>
        <input type="number" name="b" id="b" placeholder="Ingrese un número" required>
        <button type="submit" name="sumar" id="sumar_id">Sumar</button>
        <button type="submit" name="restar" id="restar_id">Restar</button>
        <button type="submit" name="multiplicar" id="multiplicar_id">Multiplicar</button>
        <button type="submit" name="dividir" id="dividir_id">Dividir</button>
    </form>
    {% include 'calculadora/components/resultado.html' %}
    <a href="{% url 'core:home' %}">Home</a>
{% endblock contenido %}

project/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}        
        {% endblock title %}
    </title>
    <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
</head>
<body>
    {% block titulo %}        
    {% endblock titulo %}
    {% block contenido %}       
    {% endblock contenido %}
</body>
</html>

project/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}
    Core
{% endblock title %}

{% block titulo %}
    <h1>App Core</h1>
{% endblock titulo %}<h1>INDEX CORE</h1>

{% block contenido %}
    <a href="{% url 'productos:home' %}">Productos</a>
    <a href="{% url 'pruebas:home' %}">Pruebas</a>
    <a href="{% url 'calculadora:home' %}">Calculadora</a>
{% endblock contenido %}

project/productos/templates/productos/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}
    Productos
{% endblock title %}

{% block titulo %}
    <h1>App Productos</h1>
{% endblock titulo %}

{% block contenido %}
    <a href="{% url 'core:home' %}">Home</a>
{% endblock contenido %}

project/pruebas/templates/pruebas/components/lista.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}
    <h2>Lista</h2>
    {% for nro in lista %}
        <p>{{nro}}</p>
    {% endfor %}
    <a href="{% url 'core:home' %}">Home</a>
{% endblock contenido %}

project/pruebas/templates/pruebas/components/select_productos.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}
    <h2>Productos</h2>
    <form method="POST" action="{% url 'pruebas:agregar_producto' %}">
        {% csrf_token %}
        {% for categoria, productos in categorias.items %}
            <select name="producto" id="producto_{{ forloop.counter }}">
                <option disabled selected>{{ categoria }}</option>
                {% for producto in productos %}
                    <option value="{{ producto.id }}">{{ producto.nombre }} ${{ producto.precio }}</option>
                {% endfor %}
            </select>
        {% endfor %}
        <input type="number" name="cantidad" placeholder="Cantidad" value="1">
        <button type="submit">Agregar</button>
    </form>
{% endblock contenido %}

project/pruebas/templates/pruebas/components/select_productos/agregar_producto.html
{% if cantidad > 0 and producto %}
    <h3>Producto agregado: {{cantidad}} {{producto.nombre}}</h3>
{% endif %}

{% if mensaje != None %}
    <h3>{{mensaje}}</h3>
{% endif %}

project/pruebas/templates/pruebas/components/select_productos/select_productos.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}
    <h1>Productos</h1>
    <form method="POST" action="{% url 'pruebas:select_productos' %}">
        {% csrf_token %}
        <div class="form-selects-conteiner">
            <div class="form-selects">
                {% for categoria, productos in categorias.items %}
                    <div class="select-container">
                        <select class="selects" name="producto" id="producto_{{ forloop.counter }}">
                            <option disabled selected>{{ categoria }}</option>
                            {% for producto in productos %}
                                <option value="{{ producto.id }}">{{ producto.nombre }} ${{ producto.precio }}</option>
                            {% endfor %}
                        </select>
                    </div>
                {% endfor %}
            </div>
            <div class="form-controls">
                <input type="number" name="cantidad" placeholder="Cantidad" value="1" min="1" required>
                <button type="submit">Agregar</button>
            </div>
        </div>
    </form>

    {% include "pruebas/components/select_productos/agregar_producto.html" %}
{% endblock contenido %}

project/pruebas/templates/pruebas/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}
    Pruebas
{% endblock title %}

{% block titulo %}
    <h1>App Pruebas</h1>
{% endblock titulo %}

{% block contenido %}
    <a href="{% url 'core:home' %}">Home</a>
    <a href="{% url 'pruebas:enviar_lista' %}">Lista</a>
    <a href="{% url 'pruebas:select_productos' %}">Select Productos</a>
    <hr>
    
{% endblock contenido %}